[workspace]
authors = ["20zero21@gmail.com <>"]
channels = ["conda-forge"]
name = "VCF-2-Clinvar-hackathon"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.4,<3.15"
pandas = ">=3.0.2,<4"
streamlit = ">=1.56.0,<2"
plotly = ">=6.6.0,<7"
python = ">=3.14.4,<3.15"
pytest = ">=9.0.3,<10"
ruff = ">=0.15.10,<0.16"
mypy = ">=1.20.1,<2"

[activation]
env = { PYTHONPATH = "." }
